name: Mapeador VivaReal

on:
  schedule:
    - cron: '0 12 * * *' # Executa 1x por dia às 9h (horário de Brasília pode variar)
  workflow_dispatch:

jobs:
  run-mapeador:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Mostrar arquivos do diretório
        run: ls -lh

      - name: Mostrar variáveis de ambiente (sem segredos)
        run: env | grep -v -i 'SECRET\|TOKEN\|PASSWORD'

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script com log detalhado
        run: |
          echo "[LOG] Iniciando execução do main.py"
          python main.py
          echo "[LOG] Execução do main.py finalizada" 